[package]
name = "linearalgebra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

pyo3 = { version = "0.18", features = ["auto-initialize"] }
numpy = "0.18"