[package]
name = "mnist-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linearalgebra = { path = "../../", features=["simd"] }
rand = "0.8.5"
csv = "1.2"